[features]
seeds = true

skip-lint = false
[programs.localnet]
bubbles = "5hH748CgCFrbuJ19GtdgaB9M1pV5VuUuTicTyz8Jhr3d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/juan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
